#!/usr/bin/env python3
#
# This script goes through all lists / repos / trackers associated to projects
# and ensures that their ResourceID is set in the respective hub database tables.

from flask import url_for
from hubsrht.app import app
from hubsrht.services.git import GitClient
from hubsrht.services.hg import HgClient
from hubsrht.services.lists import ListsClient
from hubsrht.services.todo import TodoClient
from srht.config import cfg, get_origin
from srht.database import DbSession
from srht.graphql import InternalAuth

connection_string = cfg("hub.sr.ht", "connection-string")
db = DbSession(connection_string)
db.create()

from hubsrht.types import User, MailingList, Tracker
from hubsrht.types import SourceRepo, RepoType

_listsrht = get_origin("lists.sr.ht", default=None)
_todosrht = get_origin("todo.sr.ht", default=None)
_gitsrht = get_origin("git.sr.ht", default=None)
_hgsrht = get_origin("hg.sr.ht", default=None)

print("Backfilling RIDs...")

external_origin = get_origin("hub.sr.ht", external=True)
if external_origin.startswith("https"):
    app.config['PREFERRED_URL_SCHEME'] = 'https'

external_origin = external_origin.removeprefix("http://")
external_origin = external_origin.removeprefix("https://")
app.config['SERVER_NAME'] = external_origin

with app.app_context():
    for ml in MailingList.query.all():
        if ml.remote_rid:
            print(f"RID already set for list {ml.name} - skipping")
            continue
        client = ListsClient(auth=InternalAuth(ml.owner))
        l = client.get_list(ml.name)
        if l.me.list is None:
            print(f"{ml.name} does not exist in lists.sr.ht - skipping")
            continue
        print(f"Set RID for list {ml.name} to {l.me.list.rid}")
        ml.remote_rid = l.me.list.rid
        db.session.commit()

    for repo in SourceRepo.query.all():
        if repo.repo_type == RepoType.git:
            client = GitClient(auth=InternalAuth(repo.owner))
            repo_type = 'git'
        else:
            client = HgClient(auth=InternalAuth(repo.owner))
            repo_type = 'hg'
        if repo.remote_rid:
            print(f"RID already set for {repo_type} repo {repo.name} - skipping")
            continue
        r = client.get_repo(repo.name)
        if r.me.repository is None:
            print(f"{repo.name} does not exist in {repo_type}.sr.ht - skipping")
            continue
        print(f"Set RID for repo {repo.name} to {r.me.repository.rid}")
        repo.remote_rid = r.me.repository.rid
        db.session.commit()

    for tracker in Tracker.query.all():
        if tracker.remote_rid:
            print(f"RID already set for tracker {tracker.name} - skipping")
            continue
        client = TodoClient(auth=InternalAuth(tracker.owner))
        t = client.get_tracker(tracker.name)
        if t.me.tracker is None:
            print(f"{tracker.name} does not exist in todo.sr.ht - skipping")
            continue
        print(f"Set RID for tracker {tracker.name} to {t.me.tracker.rid}")
        tracker.remote_rid = t.me.tracker.rid
        db.session.commit()

print("Done.")
