package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"strings"

	"git.sr.ht/~sircmpwn/core-go/auth"
	"git.sr.ht/~sircmpwn/core-go/database"
	gerrors "git.sr.ht/~sircmpwn/core-go/errors"
	coremodel "git.sr.ht/~sircmpwn/core-go/model"
	"git.sr.ht/~sircmpwn/core-go/server"
	"git.sr.ht/~sircmpwn/core-go/valid"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/account"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/graph/api"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/graph/model"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/loaders"
	gitclient "git.sr.ht/~sircmpwn/hub.sr.ht/api/services/git"
	hgclient "git.sr.ht/~sircmpwn/hub.sr.ht/api/services/hg"
	listsclient "git.sr.ht/~sircmpwn/hub.sr.ht/api/services/lists"
	todoclient "git.sr.ht/~sircmpwn/hub.sr.ht/api/services/todo"
	sq "github.com/Masterminds/squirrel"
	"github.com/lib/pq"
)

// Owner is the resolver for the owner field.
func (r *mailingListResolver) Owner(ctx context.Context, obj *model.MailingList) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, visibility model.Visibility, description *string, tags []string) (*model.Project, error) {
	if len(tags) > 3 {
		return nil, valid.Error(ctx, "tags", "At most 3 tags allowed")
	}
	var proj model.Project
	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		row := tx.QueryRowContext(ctx, `
			INSERT INTO project (
				created, updated, name, description, tags, visibility, owner_id
			) VALUES (
				NOW() at time zone 'utc',
				NOW() at time zone 'utc',
				$1, $2, $3, $4, $5
			) RETURNING
				id, rid,
				created, updated, name,
				description, visibility,
				tags, owner_id;
		`, name, description, pq.StringArray(tags), visibility, auth.ForContext(ctx).UserID)
		if err := row.Scan(&proj.ID, &proj.RID,
			&proj.Created, &proj.Updated, &proj.Name,
			&proj.Description, &proj.Visibility,
			pq.Array(&proj.Tags), &proj.OwnerID); err != nil {
			if strings.Contains(err.Error(), "duplicate key value violates unique constraint") {
				return valid.Error(ctx, "name", "A project with this name already exists.")
			}
			return err
		}
		return nil
	}); err != nil {
		return nil, err
	}

	return &proj, nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, rid coremodel.RID, input map[string]interface{}) (*model.Project, error) {
	projectRow, err := r.Query().Project(ctx, rid)
	if err != nil {
		return nil, err
	} else if projectRow == nil {
		return nil, gerrors.ErrNotFound
	}

	var (
		proj    model.Project
		newName string
	)
	query := sq.Update(proj.Table()).PlaceholderFormat(sq.Dollar)

	validation := valid.New(ctx).WithInput(input)
	validation.OptionalString("name", func(name string) {
		query = query.Set(`name`, name)
		newName = name
	})
	validation.Optional("visibility", func(vis interface{}) {
		query = query.Set(`visibility`, vis)
	})
	validation.NullableString("description", func(description *string) {
		if description == nil {
			query = query.Set(`description`, nil)
		} else {
			query = query.Set(`description`, *description)
		}
	})
	validation.NullableString("website", func(website *string) {
		if website == nil {
			query = query.Set(`website`, nil)
		} else {
			query = query.Set(`website`, *website)
		}
	})
	validation.OptionalBool("checklistComplete", func(b bool) {
		query = query.Set(`checklist_complete`, b)
	})
	validation.Optional("tags", func(tags interface{}) {
		switch tags := tags.(type) {
		case []string:
			if len(tags) > 3 {
				validation.Error("At most 3 tags allowed")
			}
			query = query.Set(`tags`, pq.StringArray(tags))
		default:
			validation.Error(fmt.Sprintf("Invalid type: %s", tags))
		}
	})
	if !validation.Ok() {
		return nil, errors.New("validation failed") // TODO: Avoid surfacing placeholder error
	}

	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		if len(newName) > 0 && newName != projectRow.Name {
			_, err = tx.ExecContext(ctx, `
				INSERT INTO redirect(
					created, name, owner_id, new_project_id
				)
				VALUES (
					NOW() at time zone 'utc',
					$1, $2, $3
				);
			`, projectRow.Name, projectRow.OwnerID, projectRow.ID)
			if err != nil {
				return err
			}
		}
		query = query.
			Where(`rid = ?`, rid).
			Where(`owner_id = ?`, auth.ForContext(ctx).UserID).
			Set(`updated`, sq.Expr(`now() at time zone 'utc'`)).
			Suffix(`RETURNING
				rid, created, updated, name, description, visibility,
				tags`)

		row := query.RunWith(tx).QueryRowContext(ctx)
		if err := row.Scan(&proj.RID, &proj.Created, &proj.Updated,
			&proj.Name, &proj.Description, &proj.Visibility,
			pq.Array(&proj.Tags)); err != nil {
			if err == sql.ErrNoRows {
				return gerrors.ErrNotFound
			}
			return err
		}

		return nil
	}); err != nil {
		return nil, err
	}

	return &proj, nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, rid coremodel.RID) (*model.Project, error) {
	var proj model.Project
	var listWebhookIDs, gitWebhookIDs, todoWebhookIDs []int
	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		var projectID int
		project := tx.QueryRowContext(ctx,
			"SELECT id FROM project WHERE rid = $1", rid)
		if err := project.Scan(&projectID); err != nil {
			if err == sql.ErrNoRows {
				return gerrors.ErrNotFound
			}
			return err
		}

		// Collect the associated resources' webhook IDs for clean-up
		// if the project deletion succeeds (note that hg does not
		// support repository webhooks).
		listWebhookIDs, _ = collectWebhookIDs(ctx, tx, projectID, MailingList)
		gitWebhookIDs, _ = collectWebhookIDs(ctx, tx, projectID, GitRepository)
		todoWebhookIDs, _ = collectWebhookIDs(ctx, tx, projectID, Tracker)

		row := tx.QueryRowContext(ctx, `
			DELETE FROM project
			WHERE rid = $1 AND owner_id = $2
			RETURNING
				id, rid, created, updated, name, description, visibility,
				tags, website, checklist_complete;
		`, rid, auth.ForContext(ctx).UserID)

		if err := row.Scan(&proj.ID, &proj.RID, &proj.Created, &proj.Updated,
			&proj.Name, &proj.Description, &proj.Visibility,
			pq.Array(&proj.Tags), &proj.Website, &proj.ChecklistComplete); err != nil {
			if err == sql.ErrNoRows {
				return gerrors.ErrNotFound
			}
			return err
		}
		return nil
	}); err != nil {
		return nil, err
	}

	// Best-effort clean-up of the associated webhooks.
	for _, whID := range listWebhookIDs {
		listsclient.DeleteListWebhook(
			NewListsGQLClient(ctx),
			ctx, int32(whID),
		)
	}
	for _, whID := range gitWebhookIDs {
		gitclient.DeleteRepoWebhook(
			NewGitGQLClient(ctx),
			ctx, int32(whID),
		)
	}
	for _, whID := range todoWebhookIDs {
		todoclient.DeleteTrackerWebhook(
			NewTodoGQLClient(ctx),
			ctx, int32(whID),
		)
	}

	return &proj, nil
}

// LinkMailingList is the resolver for the linkMailingList field.
func (r *mutationResolver) LinkMailingList(ctx context.Context, projectID coremodel.RID, listID coremodel.RID) (*model.MailingList, error) {
	if !Features().Lists {
		return nil, gerrors.ErrUnsupported
	}

	projectRow, err := r.Query().Project(ctx, projectID)
	if err != nil || projectRow == nil {
		return nil, gerrors.ErrNotFound
	}

	if projectRow.OwnerID != auth.ForContext(ctx).UserID {
		return nil, gerrors.ErrAccessDenied
	}

	resourceRow, err := r.Project().Resource(ctx, projectRow, listID)
	if err == nil && resourceRow != nil {
		// The list is already linked to the project
		return resourceRow.(*model.MailingList), nil
	}

	gqlList, err := listsclient.GetList(NewListsGQLClient(ctx), ctx, listID.String())
	if err != nil {
		return nil, err
	} else if gqlList == nil {
		return nil, gerrors.ErrNotFound
	}

	var ml model.MailingList
	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		row := tx.QueryRowContext(ctx, `
			INSERT INTO mailing_list (
				remote_id, remote_rid, created, updated,
				project_id, owner_id, name, description,
				visibility, webhook_id, webhook_version
			) VALUES (
				$1, $2,
				NOW() at time zone 'utc',
				NOW() at time zone 'utc',
				$3, $4, $5, $6,
				$7, -1, 0
			) RETURNING
				id, remote_rid,
				created, updated, name,
				description, visibility;
			`,
			gqlList.Id, gqlList.Rid,
			projectRow.ID, auth.ForContext(ctx).UserID,
			gqlList.Name, gqlList.Description,
			gqlList.Visibility)
		if err := row.Scan(&ml.ID, &ml.RID, &ml.Linked, &ml.Updated,
			&ml.Name, &ml.Description, &ml.Visibility); err != nil {
			return err
		}

		if err := SetupUserWebhook(ctx, tx,
			MailingList, CreateListUserWebhook); err != nil {
			return err
		}

		sub, err := listsclient.CreateListWebhook(
			NewListsGQLClient(ctx),
			ctx, gqlList.Id,
			GetWebhookURL(ctx, MailingList, ml.ID),
			listsclient.EventWebhookQuery,
		)
		if err != nil {
			return err
		}

		_, err = tx.ExecContext(ctx, `
			UPDATE mailing_list
			SET webhook_id = $1, webhook_version = $2
			WHERE id = $3;
		`, sub.Id, LISTS_WEBHOOK_VERSION, ml.ID)
		if err != nil {
			// We will rollback, so need to delete the new webhook.
			listsclient.DeleteListWebhook(
				NewListsGQLClient(ctx),
				ctx, sub.Id,
			)
			return err
		}

		return addResourceEvent(ctx, tx, projectRow.ID,
			MailingList, ml.ID, auth.ForContext(ctx).UserID)
	}); err != nil {
		return nil, err
	}

	return &ml, err
}

// UnlinkMailingList is the resolver for the unlinkMailingList field.
func (r *mutationResolver) UnlinkMailingList(ctx context.Context, projectID coremodel.RID, listID coremodel.RID) (*model.MailingList, error) {
	var ml *model.MailingList
	err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		res, err := UnlinkResource(r, ctx, tx, projectID, listID)
		if err != nil {
			return err
		}
		ml = res.(*model.MailingList)

		_, err = listsclient.DeleteListWebhook(
			NewListsGQLClient(ctx),
			ctx, int32(ml.WebhookID),
		)
		return err
	})
	return ml, err
}

// LinkSource is the resolver for the linkSource field.
func (r *mutationResolver) LinkSource(ctx context.Context, projectID coremodel.RID, sourceRepoID coremodel.RID) (*model.SourceRepo, error) {
	projectRow, err := r.Query().Project(ctx, projectID)
	if err != nil || projectRow == nil {
		return nil, gerrors.ErrNotFound
	}

	if projectRow.OwnerID != auth.ForContext(ctx).UserID {
		return nil, gerrors.ErrAccessDenied
	}

	resourceRow, err := r.Project().Resource(ctx, projectRow, sourceRepoID)
	if err == nil && resourceRow != nil {
		// The list is already linked to the project
		return resourceRow.(*model.SourceRepo), nil
	}

	var (
		gitRepo *gitclient.Repository
		hgRepo  *hgclient.Repository
	)
	if Features().Git {
		gitRepo, _ = gitclient.GetRepo(NewGitGQLClient(ctx), ctx, sourceRepoID.String())
	}
	if gitRepo == nil && Features().Hg {
		hgRepo, _ = hgclient.GetRepo(NewHgGQLClient(ctx), ctx, sourceRepoID.String())
	}
	if gitRepo == nil && hgRepo == nil {
		return nil, gerrors.ErrNotFound
	}
	repoWrapper, err := NewRepoWrapper(gitRepo, hgRepo)
	if err != nil {
		panic(err)
	}

	var rep model.SourceRepo
	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		row := tx.QueryRowContext(ctx, `
			INSERT INTO source_repo (
				remote_id, remote_rid, repo_type,
				created, updated,
				project_id, owner_id, name, description,
				visibility, webhook_id, webhook_version
			) VALUES (
				$1, $2, $3,
				NOW() at time zone 'utc',
				NOW() at time zone 'utc',
				$4, $5, $6, $7,
				$8, 0, -1
			) RETURNING
				id, remote_rid, repo_type,
				created, updated, name,
				description, visibility;
			`,
			repoWrapper.ID(), repoWrapper.RID(), repoWrapper.RepoType(),
			projectRow.ID, auth.ForContext(ctx).UserID,
			repoWrapper.Name(), repoWrapper.Description(),
			repoWrapper.Visibility())
		if err := row.Scan(&rep.ID, &rep.RID, &rep.RepoType,
			&rep.Linked, &rep.Updated,
			&rep.Name, &rep.Description, &rep.Visibility); err != nil {
			return err
		}

		if gitRepo != nil {
			if err := SetupUserWebhook(ctx, tx,
				GitRepository, CreateGitUserWebhook); err != nil {
				return err
			}

			sub, err := gitclient.CreateRepoWebhook(
				NewGitGQLClient(ctx),
				ctx, repoWrapper.ID(),
				gitclient.EventWebhookQuery,
				GetWebhookURL(ctx, GitRepository, rep.ID),
			)
			if err != nil {
				return err
			}

			_, err = tx.ExecContext(ctx, `
				UPDATE source_repo
				SET webhook_id = $1, webhook_version = $2
				WHERE id = $3;
			`, sub.Id, GIT_WEBHOOK_VERSION, rep.ID)
			if err != nil {
				// We will rollback, so need to delete the new
				// webhook.
				gitclient.DeleteRepoWebhook(
					NewGitGQLClient(ctx),
					ctx, sub.Id,
				)
				return err
			}

			return addResourceEvent(ctx, tx, projectRow.ID,
				GitRepository, rep.ID, auth.ForContext(ctx).UserID)
		} else {
			// hg.sr.ht only supports user webhooks, not repo webhooks.
			err = SetupUserWebhook(ctx, tx,
				HgRepository, CreateHgUserWebhook)
			if err != nil {
				return err
			}
			return addResourceEvent(ctx, tx, projectRow.ID,
				HgRepository, rep.ID, auth.ForContext(ctx).UserID)
		}
	}); err != nil {
		return nil, err
	}

	return &rep, err
}

// UnlinkSource is the resolver for the unlinkSource field.
func (r *mutationResolver) UnlinkSource(ctx context.Context, projectID coremodel.RID, sourceRepoID coremodel.RID) (*model.SourceRepo, error) {
	var rep *model.SourceRepo
	err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		res, err := UnlinkResource(r, ctx, tx, projectID, sourceRepoID)
		if err != nil {
			return err
		}
		rep = res.(*model.SourceRepo)
		// Repository webhooks are only supported by git.sr.ht.
		if rep.RepoType == "GIT" {
			_, err = gitclient.DeleteRepoWebhook(
				NewGitGQLClient(ctx),
				ctx, int32(rep.WebhookID),
			)
		}
		return err
	})
	return rep, err
}

// LinkTracker is the resolver for the linkTracker field.
func (r *mutationResolver) LinkTracker(ctx context.Context, projectID coremodel.RID, trackerID coremodel.RID) (*model.Tracker, error) {
	if !Features().Todo {
		return nil, gerrors.ErrUnsupported
	}

	projectRow, err := r.Query().Project(ctx, projectID)
	if err != nil || projectRow == nil {
		return nil, gerrors.ErrNotFound
	}

	if projectRow.OwnerID != auth.ForContext(ctx).UserID {
		return nil, gerrors.ErrAccessDenied
	}

	resourceRow, err := r.Project().Resource(ctx, projectRow, trackerID)
	if err == nil && resourceRow != nil {
		// The tracker is already linked to the project
		return resourceRow.(*model.Tracker), nil
	}

	gqlTracker, err := todoclient.GetTracker(NewTodoGQLClient(ctx), ctx, trackerID.String())
	if err != nil {
		return nil, err
	} else if gqlTracker == nil {
		return nil, gerrors.ErrNotFound
	}

	var trackerRow model.Tracker
	if err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		row := tx.QueryRowContext(ctx, `
			INSERT INTO tracker (
				remote_id, remote_rid, created, updated,
				project_id, owner_id, name, description,
				visibility, webhook_id, webhook_version
			) VALUES (
				$1, $2,
				NOW() at time zone 'utc',
				NOW() at time zone 'utc',
				$3, $4, $5, $6,
				$7, 0, -1
			) RETURNING
				id, remote_rid,
				created, updated, name,
				description, visibility;
			`,
			gqlTracker.Id, gqlTracker.Rid,
			projectRow.ID, auth.ForContext(ctx).UserID,
			gqlTracker.Name, gqlTracker.Description,
			gqlTracker.Visibility)
		if err := row.Scan(&trackerRow.ID, &trackerRow.RID, &trackerRow.Linked, &trackerRow.Updated,
			&trackerRow.Name, &trackerRow.Description, &trackerRow.Visibility); err != nil {
			return err
		}

		if err := SetupUserWebhook(ctx, tx,
			Tracker, CreateTrackerUserWebhook); err != nil {
			return err
		}

		sub, err := todoclient.CreateTrackerWebhook(
			NewTodoGQLClient(ctx),
			ctx, gqlTracker.Id,
			todoclient.EventWebhookQuery,
			GetWebhookURL(ctx, Tracker, trackerRow.ID),
		)
		if err != nil {
			return err
		}

		_, err = tx.ExecContext(ctx, `
			UPDATE tracker
			SET webhook_id = $1, webhook_version = $2
			WHERE id = $3;
		`, sub.Id, TODO_WEBHOOK_VERSION, trackerRow.ID)
		if err != nil {
			// We will rollback, so need to delete the new webhook.
			todoclient.DeleteTrackerWebhook(
				NewTodoGQLClient(ctx),
				ctx, sub.Id,
			)
			return err
		}
		return addResourceEvent(ctx, tx, projectRow.ID,
			Tracker, trackerRow.ID, auth.ForContext(ctx).UserID)
	}); err != nil {
		return nil, err
	}

	return &trackerRow, err
}

// UnlinkTracker is the resolver for the unlinkTracker field.
func (r *mutationResolver) UnlinkTracker(ctx context.Context, projectID coremodel.RID, trackerID coremodel.RID) (*model.Tracker, error) {
	var t *model.Tracker
	err := database.WithTx(ctx, nil, func(tx *sql.Tx) error {
		res, err := UnlinkResource(r, ctx, tx, projectID, trackerID)
		if err != nil {
			return err
		}
		t = res.(*model.Tracker)

		_, err = todoclient.DeleteTrackerWebhook(
			NewTodoGQLClient(ctx),
			ctx, int32(t.WebhookID),
		)
		return err
	})

	return t, err
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (int, error) {
	user := auth.ForContext(ctx)
	account.Delete(ctx, user.UserID, user.Username)
	return user.UserID, nil
}

// Owner is the resolver for the owner field.
func (r *projectResolver) Owner(ctx context.Context, obj *model.Project) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// MailingLists is the resolver for the mailingLists field.
func (r *projectResolver) MailingLists(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.MailingListCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var lists []*model.MailingList
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		list := (&model.MailingList{}).As(`mailing_list`)
		query := database.
			Select(ctx, list).
			From(`mailing_list`).
			Join(`project ON mailing_list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`mailing_list.visibility = 'PUBLIC'`),
				},
			})
		lists, cursor = list.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.MailingListCursor{Results: lists, Cursor: cursor}, nil
}

// Sources is the resolver for the sources field.
func (r *projectResolver) Sources(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.SourceRepoCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var sourceRepos []*model.SourceRepo
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
		query := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility = 'PUBLIC'`),
				},
			})
		sourceRepos, cursor = sourceRepo.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.SourceRepoCursor{Results: sourceRepos, Cursor: cursor}, nil
}

// Trackers is the resolver for the trackers field.
func (r *projectResolver) Trackers(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.TrackerCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var trackers []*model.Tracker
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		tracker := (&model.Tracker{}).As(`tracker`)
		query := database.
			Select(ctx, tracker).
			From(`tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility = 'PUBLIC'`),
				},
			})
		trackers, cursor = tracker.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.TrackerCursor{Results: trackers, Cursor: cursor}, nil
}

// Resource is the resolver for the resource field.
func (r *projectResolver) Resource(ctx context.Context, obj *model.Project, rid coremodel.RID) (model.ProjectResource, error) {
	var res model.ProjectResource
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		list := (&model.MailingList{}).As(`list`)
		list_row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Join(`project ON list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`list.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := list_row.Scan(database.Scan(ctx, list)...); err == nil {
			res = list
			return nil
		}
		sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
		repo_row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`source_repo.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := repo_row.Scan(database.Scan(ctx, sourceRepo)...); err == nil {
			res = sourceRepo
			return nil
		}
		tracker := (&model.Tracker{}).As(`tracker`)
		tracker_row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`tracker.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := tracker_row.Scan(database.Scan(ctx, tracker)...); err == nil {
			res = tracker
			return nil
		}
		return sql.ErrNoRows
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return res, nil
}

// MailingList is the resolver for the mailingList field.
func (r *projectResolver) MailingList(ctx context.Context, obj *model.Project, name string) (*model.MailingList, error) {
	list := (&model.MailingList{}).As(`list`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Join(`project ON list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`list.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, list)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return list, nil
}

// Source is the resolver for the source field.
func (r *projectResolver) Source(ctx context.Context, obj *model.Project, name string) (*model.SourceRepo, error) {
	sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`source_repo.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, sourceRepo)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return sourceRepo, nil
}

// Tracker is the resolver for the tracker field.
func (r *projectResolver) Tracker(ctx context.Context, obj *model.Project, name string) (*model.Tracker, error) {
	tracker := (&model.Tracker{}).As(`tracker`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`tracker.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, tracker)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return tracker, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (*model.Version, error) {
	features := Features()
	return &model.Version{
		Major:           0,
		Minor:           0,
		Patch:           0,
		BuildVersion:    server.BuildVersion,
		BuildDate:       server.BuildDate,
		DeprecationDate: nil,

		Features: &features,
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := auth.ForContext(ctx)
	return &model.User{
		ID:       user.UserID,
		Username: user.Username,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	return loaders.ForContext(ctx).UsersByName.Load(username)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, rid coremodel.RID) (*model.Project, error) {
	proj := (&model.Project{}).As(`proj`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, proj).
			From(`project proj`).
			Where(sq.And{
				sq.Expr(`proj.rid = ?`, rid),
				sq.Or{
					sq.Expr(`proj.owner_id = ?`, user.UserID),
					sq.Expr(`proj.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, proj)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return proj, nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context, cursor *coremodel.Cursor) (*model.ProjectCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var projects []*model.Project
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		project := (&model.Project{}).As(`project`)
		query := database.
			Select(ctx, project).
			From(`project`).
			Where(sq.Expr(`project.visibility = 'PUBLIC'`))
		projects, cursor = project.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.ProjectCursor{Results: projects, Cursor: cursor}, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, rid coremodel.RID) (model.ProjectResource, error) {
	if list, err := r.MailingList(ctx, rid); err == nil && list != nil {
		return list, err
	}
	if sourceRepo, err := r.Source(ctx, rid); err == nil && sourceRepo != nil {
		return sourceRepo, err
	}
	if tracker, err := r.Tracker(ctx, rid); err == nil && tracker != nil {
		return tracker, err
	}
	return nil, nil
}

// MailingList is the resolver for the mailingList field.
func (r *queryResolver) MailingList(ctx context.Context, rid coremodel.RID) (*model.MailingList, error) {
	list := (&model.MailingList{}).As(`list`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Where(sq.And{
				sq.Expr(`list.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`list.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, list)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return list, nil
}

// Source is the resolver for the source field.
func (r *queryResolver) Source(ctx context.Context, rid coremodel.RID) (*model.SourceRepo, error) {
	sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Where(sq.And{
				sq.Expr(`source_repo.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`source_repo.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, sourceRepo)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return sourceRepo, nil
}

// Tracker is the resolver for the tracker field.
func (r *queryResolver) Tracker(ctx context.Context, rid coremodel.RID) (*model.Tracker, error) {
	tracker := (&model.Tracker{}).As(`tracker`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Where(sq.And{
				sq.Expr(`tracker.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`tracker.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, tracker)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return tracker, nil
}

// Owner is the resolver for the owner field.
func (r *sourceRepoResolver) Owner(ctx context.Context, obj *model.SourceRepo) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// Owner is the resolver for the owner field.
func (r *trackerResolver) Owner(ctx context.Context, obj *model.Tracker) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// Project is the resolver for the project field.
func (r *userResolver) Project(ctx context.Context, obj *model.User, name string) (*model.Project, error) {
	project := (&model.Project{}).As(`project`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, project).
			From(`project`).
			Where(sq.And{
				sq.Expr(`project.owner_id = ?`, obj.ID),
				sq.Expr(`project.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`project.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, project)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return project, nil
}

// Projects is the resolver for the projects field.
func (r *userResolver) Projects(ctx context.Context, obj *model.User, cursor *coremodel.Cursor) (*model.ProjectCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var projects []*model.Project
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		project := (&model.Project{}).As(`project`)
		user := auth.ForContext(ctx)
		query := database.
			Select(ctx, project).
			From(`project`).
			Where(sq.And{
				sq.Expr(`project.owner_id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`project.visibility = 'PUBLIC'`),
				},
			})
		projects, cursor = project.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.ProjectCursor{Results: projects, Cursor: cursor}, nil
}

// MailingList returns api.MailingListResolver implementation.
func (r *Resolver) MailingList() api.MailingListResolver { return &mailingListResolver{r} }

// Mutation returns api.MutationResolver implementation.
func (r *Resolver) Mutation() api.MutationResolver { return &mutationResolver{r} }

// Project returns api.ProjectResolver implementation.
func (r *Resolver) Project() api.ProjectResolver { return &projectResolver{r} }

// Query returns api.QueryResolver implementation.
func (r *Resolver) Query() api.QueryResolver { return &queryResolver{r} }

// SourceRepo returns api.SourceRepoResolver implementation.
func (r *Resolver) SourceRepo() api.SourceRepoResolver { return &sourceRepoResolver{r} }

// Tracker returns api.TrackerResolver implementation.
func (r *Resolver) Tracker() api.TrackerResolver { return &trackerResolver{r} }

// User returns api.UserResolver implementation.
func (r *Resolver) User() api.UserResolver { return &userResolver{r} }

type mailingListResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sourceRepoResolver struct{ *Resolver }
type trackerResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
