package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.64

import (
	"context"
	"database/sql"

	"git.sr.ht/~sircmpwn/core-go/auth"
	"git.sr.ht/~sircmpwn/core-go/config"
	"git.sr.ht/~sircmpwn/core-go/database"
	coremodel "git.sr.ht/~sircmpwn/core-go/model"
	"git.sr.ht/~sircmpwn/core-go/server"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/account"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/graph/api"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/graph/model"
	"git.sr.ht/~sircmpwn/hub.sr.ht/api/loaders"
	sq "github.com/Masterminds/squirrel"
)

// Owner is the resolver for the owner field.
func (r *mailingListResolver) Owner(ctx context.Context, obj *model.MailingList) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context) (int, error) {
	user := auth.ForContext(ctx)
	account.Delete(ctx, user.UserID, user.Username)
	return user.UserID, nil
}

// Owner is the resolver for the owner field.
func (r *projectResolver) Owner(ctx context.Context, obj *model.Project) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// MailingLists is the resolver for the mailingLists field.
func (r *projectResolver) MailingLists(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.MailingListCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var lists []*model.MailingList
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		list := (&model.MailingList{}).As(`mailing_list`)
		query := database.
			Select(ctx, list).
			From(`mailing_list`).
			Join(`project ON mailing_list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`mailing_list.visibility = 'PUBLIC'`),
				},
			})
		lists, cursor = list.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.MailingListCursor{Results: lists, Cursor: cursor}, nil
}

// Sources is the resolver for the sources field.
func (r *projectResolver) Sources(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.SourceRepoCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var sourceRepos []*model.SourceRepo
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
		query := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility = 'PUBLIC'`),
				},
			})
		sourceRepos, cursor = sourceRepo.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.SourceRepoCursor{Results: sourceRepos, Cursor: cursor}, nil
}

// Trackers is the resolver for the trackers field.
func (r *projectResolver) Trackers(ctx context.Context, obj *model.Project, cursor *coremodel.Cursor) (*model.TrackerCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var trackers []*model.Tracker
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		tracker := (&model.Tracker{}).As(`tracker`)
		query := database.
			Select(ctx, tracker).
			From(`tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility = 'PUBLIC'`),
				},
			})
		trackers, cursor = tracker.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.TrackerCursor{Results: trackers, Cursor: cursor}, nil
}

// Resource is the resolver for the resource field.
func (r *projectResolver) Resource(ctx context.Context, obj *model.Project, rid coremodel.RID) (model.ProjectResource, error) {
	var res model.ProjectResource
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		list := (&model.MailingList{}).As(`list`)
		list_row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Join(`project ON list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`list.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := list_row.Scan(database.Scan(ctx, list)...); err == nil {
			res = list
			return nil
		}
		sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
		repo_row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`source_repo.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := repo_row.Scan(database.Scan(ctx, sourceRepo)...); err == nil {
			res = sourceRepo
			return nil
		}
		tracker := (&model.Tracker{}).As(`tracker`)
		tracker_row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`tracker.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		if err := tracker_row.Scan(database.Scan(ctx, tracker)...); err == nil {
			res = tracker
			return nil
		}
		return sql.ErrNoRows
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return res, nil
}

// MailingList is the resolver for the mailingList field.
func (r *projectResolver) MailingList(ctx context.Context, obj *model.Project, name string) (*model.MailingList, error) {
	list := (&model.MailingList{}).As(`list`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Join(`project ON list.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`list.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, list)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return list, nil
}

// Source is the resolver for the source field.
func (r *projectResolver) Source(ctx context.Context, obj *model.Project, name string) (*model.SourceRepo, error) {
	sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Join(`project ON source_repo.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`source_repo.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, sourceRepo)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return sourceRepo, nil
}

// Tracker is the resolver for the tracker field.
func (r *projectResolver) Tracker(ctx context.Context, obj *model.Project, name string) (*model.Tracker, error) {
	tracker := (&model.Tracker{}).As(`tracker`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Join(`project ON tracker.project_id = project.id`).
			Where(sq.And{
				sq.Expr(`project.id = ?`, obj.ID),
				sq.Expr(`tracker.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, tracker)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return tracker, nil
}

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (*model.Version, error) {
	conf := config.ForContext(ctx)
	return &model.Version{
		Major:           0,
		Minor:           0,
		Patch:           0,
		BuildVersion:    server.BuildVersion,
		BuildDate:       server.BuildDate,
		DeprecationDate: nil,

		Features: &model.Features{
			Lists: len(config.GetOrigin(conf, "lists.sr.ht", true)) > 0,
			Git:   len(config.GetOrigin(conf, "git.sr.ht", true)) > 0,
			Hg:    len(config.GetOrigin(conf, "hg.sr.ht", true)) > 0,
			Todo:  len(config.GetOrigin(conf, "todo.sr.ht", true)) > 0,
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	user := auth.ForContext(ctx)
	return &model.User{
		ID:       user.UserID,
		Username: user.Username,
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, username string) (*model.User, error) {
	return loaders.ForContext(ctx).UsersByName.Load(username)
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, rid coremodel.RID) (*model.Project, error) {
	proj := (&model.Project{}).As(`proj`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, proj).
			From(`project proj`).
			Where(sq.And{
				sq.Expr(`proj.rid = ?`, rid),
				sq.Or{
					sq.Expr(`proj.owner_id = ?`, user.UserID),
					sq.Expr(`proj.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, proj)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return proj, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, rid coremodel.RID) (model.ProjectResource, error) {
	if list, err := r.MailingList(ctx, rid); err == nil && list != nil {
		return list, err
	}
	if sourceRepo, err := r.Source(ctx, rid); err == nil && sourceRepo != nil {
		return sourceRepo, err
	}
	if tracker, err := r.Tracker(ctx, rid); err == nil && tracker != nil {
		return tracker, err
	}
	return nil, nil
}

// MailingList is the resolver for the mailingList field.
func (r *queryResolver) MailingList(ctx context.Context, rid coremodel.RID) (*model.MailingList, error) {
	list := (&model.MailingList{}).As(`list`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, list).
			From(`mailing_list list`).
			Where(sq.And{
				sq.Expr(`list.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`list.owner_id = ?`, user.UserID),
					sq.Expr(`list.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, list)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return list, nil
}

// Source is the resolver for the source field.
func (r *queryResolver) Source(ctx context.Context, rid coremodel.RID) (*model.SourceRepo, error) {
	sourceRepo := (&model.SourceRepo{}).As(`source_repo`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, sourceRepo).
			From(`source_repo`).
			Where(sq.And{
				sq.Expr(`source_repo.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`source_repo.owner_id = ?`, user.UserID),
					sq.Expr(`source_repo.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, sourceRepo)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return sourceRepo, nil
}

// Tracker is the resolver for the tracker field.
func (r *queryResolver) Tracker(ctx context.Context, rid coremodel.RID) (*model.Tracker, error) {
	tracker := (&model.Tracker{}).As(`tracker`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, tracker).
			From(`tracker tracker`).
			Where(sq.And{
				sq.Expr(`tracker.remote_rid = ?`, rid.String()),
				sq.Or{
					sq.Expr(`tracker.owner_id = ?`, user.UserID),
					sq.Expr(`tracker.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, tracker)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return tracker, nil
}

// Owner is the resolver for the owner field.
func (r *sourceRepoResolver) Owner(ctx context.Context, obj *model.SourceRepo) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// Owner is the resolver for the owner field.
func (r *trackerResolver) Owner(ctx context.Context, obj *model.Tracker) (model.Entity, error) {
	return loaders.ForContext(ctx).UsersByID.Load(obj.OwnerID)
}

// Project is the resolver for the project field.
func (r *userResolver) Project(ctx context.Context, obj *model.User, name string) (*model.Project, error) {
	project := (&model.Project{}).As(`project`)
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		user := auth.ForContext(ctx)
		row := database.
			Select(ctx, project).
			From(`project`).
			Where(sq.And{
				sq.Expr(`project.owner_id = ?`, obj.ID),
				sq.Expr(`project.name = ?`, name),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`project.visibility != 'PRIVATE'`),
				},
			}).
			RunWith(tx).
			QueryRowContext(ctx)
		return row.Scan(database.Scan(ctx, project)...)
	}); err != nil {
		if err == sql.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return project, nil
}

// Projects is the resolver for the projects field.
func (r *userResolver) Projects(ctx context.Context, obj *model.User, cursor *coremodel.Cursor) (*model.ProjectCursor, error) {
	if cursor == nil {
		cursor = coremodel.NewCursor(nil)
	}

	var projects []*model.Project
	if err := database.WithTx(ctx, &sql.TxOptions{
		Isolation: 0,
		ReadOnly:  true,
	}, func(tx *sql.Tx) error {
		project := (&model.Project{}).As(`project`)
		user := auth.ForContext(ctx)
		query := database.
			Select(ctx, project).
			From(`project`).
			Where(sq.And{
				sq.Expr(`project.owner_id = ?`, obj.ID),
				sq.Or{
					sq.Expr(`project.owner_id = ?`, user.UserID),
					sq.Expr(`project.visibility = 'PUBLIC'`),
				},
			})
		projects, cursor = project.QueryWithCursor(ctx, tx, query, cursor)
		return nil
	}); err != nil {
		return nil, err
	}

	return &model.ProjectCursor{Results: projects, Cursor: cursor}, nil
}

// MailingList returns api.MailingListResolver implementation.
func (r *Resolver) MailingList() api.MailingListResolver { return &mailingListResolver{r} }

// Mutation returns api.MutationResolver implementation.
func (r *Resolver) Mutation() api.MutationResolver { return &mutationResolver{r} }

// Project returns api.ProjectResolver implementation.
func (r *Resolver) Project() api.ProjectResolver { return &projectResolver{r} }

// Query returns api.QueryResolver implementation.
func (r *Resolver) Query() api.QueryResolver { return &queryResolver{r} }

// SourceRepo returns api.SourceRepoResolver implementation.
func (r *Resolver) SourceRepo() api.SourceRepoResolver { return &sourceRepoResolver{r} }

// Tracker returns api.TrackerResolver implementation.
func (r *Resolver) Tracker() api.TrackerResolver { return &trackerResolver{r} }

// User returns api.UserResolver implementation.
func (r *Resolver) User() api.UserResolver { return &userResolver{r} }

type mailingListResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type sourceRepoResolver struct{ *Resolver }
type trackerResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
